name: release-please

on:
  push:
    branches:
      - main
  
jobs:
  release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR with release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
  
      # release-please is unable to update uv.lock, so we do it ourselves
      # https://github.com/googleapis/release-please/issues/2455#issuecomment-2569782706
      # https://github.com/astral-sh/uv/issues/7533

      - name: Debug context
        run: |
          echo "PR context: ${{ fromJson(steps.release-please.outputs) }}"

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(steps.release-please.outputs.pr).headBranchName }}

      - name: Setup `uv`
        uses: astral-sh/setup-uv@v6

      - name: Update `uv.lock`
        run: |
          uv lock
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add uv.lock
          git commit -m "ci: update uv.lock"
          git push
